# Generated by Django 4.0 on 2022-02-03 09:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiereclasse',
            old_name='enseigant',
            new_name='enseignant',
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
