# Generated by Django 4.0 on 2022-02-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0002_rename_enseigant_matiereclasse_enseignant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoupage',
            name='nom',
        ),
    ]
