# Generated by Django 4.0 on 2022-02-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_remove_decoupage_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
