# Generated by Django 4.0 on 2022-03-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0004_alter_etablissement_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='titulaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulaire', to='etablissements.enseignant'),
        ),
        migrations.AddField(
            model_name='dre',
            name='drapeau',
            field=models.FileField(blank=True, null=True, upload_to='pays'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='ets'),
        ),
    ]
