# Generated by Django 4.0 on 2022-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0005_classe_titulaire_dre_drapeau_etablissement_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='eff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='moygen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='moygen1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='moygen2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='moygen3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
