# Generated by Django 4.0 on 2022-03-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0007_classe_max_classe_max1_classe_max2_classe_max3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to='ets/plan'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='ens'),
        ),
    ]
