# Generated by Django 4.0 on 2022-03-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0009_alter_dre_drapeau_alter_etablissement_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ManyToManyField(null=True, to='etablissements.Classe')),
                ('periode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='etablissements.decoupage')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'db_table': 'examen',
            },
        ),
    ]
