# Generated by Django 4.0 on 2022-03-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0012_alter_examen_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Facultative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscomp', models.BooleanField(default=False)),
                ('coef', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ManyToManyField(null=True, related_name='facultatives', to='etablissements.Classe')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mfacultatives', to='etablissements.matiere')),
            ],
            options={
                'verbose_name': 'Matière Facultative',
                'verbose_name_plural': 'Matières Facultatives',
                'db_table': 'facultative',
            },
        ),
    ]
