# Generated by Django 4.0 on 2022-03-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0013_etablissement_bp_facultative'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='ville',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
