# Generated by Django 4.0 on 2022-02-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=256, null=True)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Nouvelle', 'Nouvelle'), ('Redoublant', 'Redoublant'), ('Redoublante', 'Redoublante')], max_length=256, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='etablissements.classe')),
            ],
            options={
                'verbose_name': 'Elève',
                'verbose_name_plural': 'Elèves',
                'db_table': 'eleve',
            },
        ),
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moy', models.IntegerField(blank=True, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='bulletin.eleve')),
                ('periode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='etablissements.decoupage')),
            ],
            options={
                'verbose_name': 'Moyenne',
                'verbose_name_plural': 'Moyennes',
                'db_table': 'moyenne',
            },
        ),
        migrations.CreateModel(
            name='MoyenneMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interro', models.IntegerField(blank=True, null=True)),
                ('devoir', models.IntegerField(blank=True, null=True)),
                ('compo', models.IntegerField(blank=True, null=True)),
                ('moycl', models.IntegerField(blank=True, null=True)),
                ('moymat', models.IntegerField(blank=True, null=True)),
                ('moycoef', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyennesclasse', to='etablissements.matiereclasse')),
                ('moy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyennesgen', to='bulletin.moyenne')),
            ],
            options={
                'verbose_name': 'Moyenne du Matière',
                'verbose_name_plural': 'Moyennes des Matières',
                'db_table': 'moyenne_matiere',
            },
        ),
    ]
