# Generated by Django 4.0 on 2022-02-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenne',
            name='moy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moyennematiere',
            name='compo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moyennematiere',
            name='devoir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moyennematiere',
            name='interro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moyennematiere',
            name='moycl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moyennematiere',
            name='moycoef',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moyennematiere',
            name='moymat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
