# Generated by Django 4.0 on 2022-02-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_alter_moyenne_moy_alter_moyennematiere_compo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyennematiere',
            name='moy',
        ),
    ]
