# Generated by Django 4.0 on 2022-02-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_eleve_moy1_eleve_moy2_eleve_moy3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyenne',
            name='eleve',
        ),
        migrations.AddField(
            model_name='moyennematiere',
            name='eleve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='bulletin.eleve'),
        ),
        migrations.AlterField(
            model_name='moyennematiere',
            name='compo',
            field=models.FloatField(null=True),
        ),
    ]
