# Generated by Django 4.0 on 2022-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_remove_moyenne_eleve_moyennematiere_eleve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='rang1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='rang3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moyennematiere',
            name='rang',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
