# Generated by Django 4.0 on 2022-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0007_eleve_rang2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moyennematiere',
            options={'ordering': ['-moymat'], 'verbose_name': 'Moyenne du Matière', 'verbose_name_plural': 'Moyennes des Matières'},
        ),
        migrations.AddField(
            model_name='eleve',
            name='tot1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='totcoef',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
