# Generated by Django 4.0 on 2022-03-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0008_alter_moyennematiere_options_eleve_tot1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='eleves'),
        ),
    ]
